version: 2

sources:
  - name: bronze
    description: "Raw data landing zone from streaming pipeline"
    database: DEV_DB
    schema: BRONZE
    tables:
      - name: raw_events
        description: "Raw event data from Kafka ingestion"
        columns:
          - name: event_id
            description: "Unique identifier for each event"
          - name: event_type
            description: "Type of event (CLICK, VIEW, PURCHASE, etc.)"
          - name: payload
            description: "JSON payload containing event details"
          - name: created_at
            description: "Timestamp when event was created"